### ISSUE TITLE
Get rid of rounding errors

### ISSUE THREAD

**Issue by steffenbrand** [xyNNN/unicorn#4]
http://martinfowler.com/eaaCatalog/money.html

There are some implementations on packagist:
https://packagist.org/packages/mathiasverraes/money

![rounding-error](https://cloud.githubusercontent.com/assets/5013806/19511114/2cdc5b14-95e6-11e6-86f6-748f92777332.png)

**Comment by xyNNN** [comment]
Perhaps we can use this library (see https://github.com/moneyphp/money)

**Comment by steffenbrand** [comment]
Maybe the BC Math functions could also be a general solution, as they also work with strings, but aren't espacially made only for monetary values: http://php.net/manual/de/ref.bc.php

See example in bcadd:
http://php.net/manual/de/function.bcadd.php

I will give this a try, because I think it's way faster to implement and the results might be the same.

**Comment by steffenbrand** [comment]
Thanks to BC Math the rounding errors should be gone now.
But I limited the decimals to 999, to avoid performance issues, as the execution time and memory usage growth exponentially to the number of decimals used.
